version: '3.9'
services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  teddy-api:
    build: .
    container_name: teddy-api
    restart: always
    env_file: ./.env
    environment:
      DB_HOST: "postgres"
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      ENV: $ENV
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata: